version: '3.6'
services:
  web:
    image: nginx:alpine
    ports:
      - "1003:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rabbit_mq_tutorial
  rabbit:
    image: rabbitmq:latest
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit_mq_tutorial
  php:
    build:
      context: .
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - rabbit_mq_tutorial
    depends_on:
      - web
      - database
      - rabbit
  database:
    image: mysql:5.7
    ports:
      - "3308:3308"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - rabbitmqphp_data:/var/lib/mysql
    networks:
      - rabbit_mq_tutorial
networks:
  rabbit_mq_tutorial:
    name: rabbit_mq_tutorial
    driver: bridge

volumes:
  rabbitmqphp_data:
    driver: local
